function [fitresult, gof] = createFit(r, C)
%CREATEFIT(R,C)
%  Create a fit.
%
%  Data for 'Cr/R' fit:
%      X Input : r
%      Y Output: C
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 03-Jun-2015 12:55:25


%% Fit: 'Cr/R'.
[xData, yData] = prepareCurveData( r, C );

% Set up fittype and options.
ft = fittype( 'poly6' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'Cr/R' );
h = plot( fitresult, xData, yData );
legend( h, 'C vs. r', 'Cr/R', 'Location', 'NorthEast' );
% Label axes
xlabel r
ylabel C
grid on


