%Z = deg2rad(45);
%Y = deg2rad(0);
%X = deg2rad(45);
syms Z;
syms Y;
syms X;
syms Tt;
x = deg2rad(45);
y = deg2rad(0);
z = deg2rad(0);
%rz = [ cos(z) -sin(z) 0; sin(z) cos(z) 0; 0 0 1];
%ry = [cos(y) 0 sin(y); 0 1 0; -sin(y) 0 cos(y)];
%rx = [1 0 0; 0 cos(x) -sin(x); 0 sin(x) cos(x)];
Qx = [cos(x/2) sin(x/2) 0 0];
Qy = [cos(y/2) 0 sin(y/2) 0];
Qz = [cos(z/2) 0 0 sin(z/2)];
Qb = quatmultiply(Qz,quatmultiply(Qy,Qx));
Qbi = quatinv(Qb);
T = [0 0 0 -1];
Tp = quatmultiply(Qbi,quatmultiply(T,Qb));
disp(Tp);
