Z = deg2rad(45);
%y = deg2rad(53.41);
%x = deg2rad(35.26);
%syms z;
syms Y;
syms X;
syms Tt;
x = -X;
y = -Y;
z = -Z;
rz = [ cos(z) -sin(z) 0; sin(z) cos(z) 0; 0 0 1];
ry = [cos(y) 0 sin(y); 0 1 0; -sin(y) 0 cos(y)];
rx = [1 0 0; 0 cos(x) -sin(x); 0 sin(x) cos(x)];
T = [0 0 Tt].';
disp((rz*ry*rx)*T);
